// Common HTTP response status codes

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
  CIRCUIT_BREAKER_OPEN_CODE: 'CIRCUIT_OPEN',
  OPEN_API_VALIDATION_ERROR: 'format.openapi.validation',
} as const;
